# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: NeoML/docs/en/Python/conf.py

# Optionally build your docs in additional formats such as PDF
# formats:
#    - html

# Optionally set the version of Python and requirements required to build your docs
python:
   version: 3.6
   install:
   - requirements: NeoML/docs/en/Python/requirements.txt
   - method: setuptools
     path: NeoML/Python
