name: neoml-docs

channels:
    - conda-forge
    - defaults

dependencies:
    - python>=3.6
    - anaconda
    - pip
    - sphinx
    - m2r2
    - pybind11
    - cmake
    - ninja
    - protobuf
    - mkl_devel
    - numpy
    - scipy
